title: |
  Energie­beratung
  Peter Gehring
url: https://energieberatung-gehring.de
baseurl: ""

profile_picture: peter_gehring.jpg

email: p_gehring@web.de
phone: 01783 1783 25
address : |
  Karolingerring 25
  63791 Karlstein a. M.

exclude:
  - Gemfile
  - Gemfile.lock
  - default.nix
  - gemset.nix
  - vendor
  - node_modules
  - package-lock.json
  - package.json
